apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: cart-deployment 
spec:
  replicas: 2
  selector: 
    matchLabels:
      web: app 
  template:
    metadata:
      labels:
        web: app 
    spec: 
      containers:
        - name: cart-container 
          image: muralisocial123/cart-page-example:1.0
          ports:
            - containerPort: 3000